spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/veterandb
    username: veteran
    password: veteran
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#      jakarta:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              create-target: create.sql
#              action: create
  flyway:
    baseline-on-migrate: false
    baseline-version: 1
    enabled: true
    locations: classpath:db/migrations
    user: veteran
    password: veteran


cors:
  origins: > 
    http://localhost:3000,
    http://localhost:3001

security:
  secret: ${SECRET_KEY}
