spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSERNAME}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: false
    baseline-version: 1
    enabled: true
    locations: classpath:db/migrations
    user: ${PGUSERNAME}
    password: ${PGPASSWORD}

cors:
  origins: >
    ${USER_ACCESS_POINT},
    ${ADMIN_ACCESS_POINT}

security:
  secret: ${SECRET_KEY}

